# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['SyntheticDataset']

# %% ../nbs/00_core.ipynb 3
class SyntheticDataset:
    def __init__(self, generator, representer): ...
