# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_symbolic_representers.ipynb.

# %% auto 0
__all__ = ['ImageRepresenter', 'VideoRepresenter', 'WebSiteRepresenter']

# %% ../nbs/01_symbolic_representers.ipynb 3
class ImageRepresenter:
    pass

# %% ../nbs/01_symbolic_representers.ipynb 4
class VideoRepresenter:
    pass

# %% ../nbs/01_symbolic_representers.ipynb 5
class WebSiteRepresenter:
    """
    Based on WebArena: https://arxiv.org/pdf/2307.13854.pdf
    """

    pass
